[book]
title = "codescout Manual"
authors = ["Marius"]
language = "en"
src = "src"

[build]
build-dir = "../../target/manual"

[output.html]
git-repository-url = "https://github.com/mareurs/codescout"
edit-url-template = "https://github.com/mareurs/codescout/edit/master/docs/manual/{path}"
no-section-label = false
